package com.raaveinm.chirro.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

data object MonochromeColors {
    val primaryLight = Color(0xFF000000)
    val onPrimaryLight = Color(0xFFFFFFFF)
    val primaryContainerLight = Color(0xFF1B1B1B)
    val onPrimaryContainerLight = Color(0xFF848484)
    val secondaryLight = Color(0xFF5E5E5E)
    val onSecondaryLight = Color(0xFFFFFFFF)
    val secondaryContainerLight = Color(0xFFE2E2E2)
    val onSecondaryContainerLight = Color(0xFF646464)
    val tertiaryLight = Color(0xFF000000)
    val onTertiaryLight = Color(0xFFFFFFFF)
    val tertiaryContainerLight = Color(0xFF1B1B1B)
    val onTertiaryContainerLight = Color(0xFF848484)
    val errorLight = Color(0xFFBA1A1A)
    val onErrorLight = Color(0xFFFFFFFF)
    val errorContainerLight = Color(0xFFFFDAD6)
    val onErrorContainerLight = Color(0xFF93000A)
    val backgroundLight = Color(0xFFF9F9F9)
    val onBackgroundLight = Color(0xFF1B1B1B)
    val surfaceLight = Color(0xFFF9F9F9)
    val onSurfaceLight = Color(0xFF1B1B1B)
    val surfaceVariantLight = Color(0xFFEBE0E1)
    val onSurfaceVariantLight = Color(0xFF4C4546)
    val outlineLight = Color(0xFF7E7576)
    val outlineVariantLight = Color(0xFFCFC4C5)
    val scrimLight = Color(0xFF000000)
    val inverseSurfaceLight = Color(0xFF303030)
    val inverseOnSurfaceLight = Color(0xFFF1F1F1)
    val inversePrimaryLight = Color(0xFFC6C6C6)
    val surfaceDimLight = Color(0xFFDADADA)
    val surfaceBrightLight = Color(0xFFF9F9F9)
    val surfaceContainerLowestLight = Color(0xFFFFFFFF)
    val surfaceContainerLowLight = Color(0xFFF3F3F3)
    val surfaceContainerLight = Color(0xFFEEEEEE)
    val surfaceContainerHighLight = Color(0xFFE8E8E8)
    val surfaceContainerHighestLight = Color(0xFFE2E2E2)

    val primaryDark = Color(0xFFC6C6C6)
    val onPrimaryDark = Color(0xFF303030)
    val primaryContainerDark = Color(0xFF000000)
    val onPrimaryContainerDark = Color(0xFF757575)
    val secondaryDark = Color(0xFFC6C6C6)
    val onSecondaryDark = Color(0xFF303030)
    val secondaryContainerDark = Color(0xFF474747)
    val onSecondaryContainerDark = Color(0xFFB5B5B5)
    val tertiaryDark = Color(0xFFC6C6C6)
    val onTertiaryDark = Color(0xFF303030)
    val tertiaryContainerDark = Color(0xFF000000)
    val onTertiaryContainerDark = Color(0xFF757575)
    val errorDark = Color(0xFFFFB4AB)
    val onErrorDark = Color(0xFF690005)
    val errorContainerDark = Color(0xFF93000A)
    val onErrorContainerDark = Color(0xFFFFDAD6)
    val backgroundDark = Color(0xFF131313)
    val onBackgroundDark = Color(0xFFE2E2E2)
    val surfaceDark = Color(0xFF131313)
    val onSurfaceDark = Color(0xFFE2E2E2)
    val surfaceVariantDark = Color(0xFF4C4546)
    val onSurfaceVariantDark = Color(0xFFCFC4C5)
    val outlineDark = Color(0xFF988E90)
    val outlineVariantDark = Color(0xFF4C4546)
    val scrimDark = Color(0xFF000000)
    val inverseSurfaceDark = Color(0xFFE2E2E2)
    val inverseOnSurfaceDark = Color(0xFF303030)
    val inversePrimaryDark = Color(0xFF5E5E5E)
    val surfaceDimDark = Color(0xFF131313)
    val surfaceBrightDark = Color(0xFF393939)
    val surfaceContainerLowestDark = Color(0xFF0E0E0E)
    val surfaceContainerLowDark = Color(0xFF1B1B1B)
    val surfaceContainerDark = Color(0xFF1F1F1F)
    val surfaceContainerHighDark = Color(0xFF2A2A2A)
    val surfaceContainerHighestDark = Color(0xFF353535)


    val monochromeLightScheme = lightColorScheme(
        primary = primaryLight,
        onPrimary = onPrimaryLight,
        primaryContainer = primaryContainerLight,
        onPrimaryContainer = onPrimaryContainerLight,
        secondary = secondaryLight,
        onSecondary = onSecondaryLight,
        secondaryContainer = secondaryContainerLight,
        onSecondaryContainer = onSecondaryContainerLight,
        tertiary = tertiaryLight,
        onTertiary = onTertiaryLight,
        tertiaryContainer = tertiaryContainerLight,
        onTertiaryContainer = onTertiaryContainerLight,
        error = errorLight,
        onError = onErrorLight,
        errorContainer = errorContainerLight,
        onErrorContainer = onErrorContainerLight,
        background = backgroundLight,
        onBackground = onBackgroundLight,
        surface = surfaceLight,
        onSurface = onSurfaceLight,
        surfaceVariant = surfaceVariantLight,
        onSurfaceVariant = onSurfaceVariantLight,
        outline = outlineLight,
        outlineVariant = outlineVariantLight,
        scrim = scrimLight,
        inverseSurface = inverseSurfaceLight,
        inverseOnSurface = inverseOnSurfaceLight,
        inversePrimary = inversePrimaryLight,
        surfaceDim = surfaceDimLight,
        surfaceBright = surfaceBrightLight,
        surfaceContainerLowest = surfaceContainerLowestLight,
        surfaceContainerLow = surfaceContainerLowLight,
        surfaceContainer = surfaceContainerLight,
        surfaceContainerHigh = surfaceContainerHighLight,
        surfaceContainerHighest = surfaceContainerHighestLight,
    )

    val monochromeDarkScheme = darkColorScheme(
        primary = primaryDark,
        onPrimary = onPrimaryDark,
        primaryContainer = primaryContainerDark,
        onPrimaryContainer = onPrimaryContainerDark,
        secondary = secondaryDark,
        onSecondary = onSecondaryDark,
        secondaryContainer = secondaryContainerDark,
        onSecondaryContainer = onSecondaryContainerDark,
        tertiary = tertiaryDark,
        onTertiary = onTertiaryDark,
        tertiaryContainer = tertiaryContainerDark,
        onTertiaryContainer = onTertiaryContainerDark,
        error = errorDark,
        onError = onErrorDark,
        errorContainer = errorContainerDark,
        onErrorContainer = onErrorContainerDark,
        background = backgroundDark,
        onBackground = onBackgroundDark,
        surface = surfaceDark,
        onSurface = onSurfaceDark,
        surfaceVariant = surfaceVariantDark,
        onSurfaceVariant = onSurfaceVariantDark,
        outline = outlineDark,
        outlineVariant = outlineVariantDark,
        scrim = scrimDark,
        inverseSurface = inverseSurfaceDark,
        inverseOnSurface = inverseOnSurfaceDark,
        inversePrimary = inversePrimaryDark,
        surfaceDim = surfaceDimDark,
        surfaceBright = surfaceBrightDark,
        surfaceContainerLowest = surfaceContainerLowestDark,
        surfaceContainerLow = surfaceContainerLowDark,
        surfaceContainer = surfaceContainerDark,
        surfaceContainerHigh = surfaceContainerHighDark,
        surfaceContainerHighest = surfaceContainerHighestDark,
    )
}